apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    web: app
spec:
   replicas: 3
   selector :
     matchLabels:
      web: app
   template:
    metadata:
     labels:
      web: app
    spec:
      containers:
      - name : mycantainer
        image :  vimal13/apache-webserver-php:v3

